name: AutoBufGenerate

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
    
env:
  EMAIL_ACTOR: passawat@passawat.passawat
  CI_COMMIT_MESSAGE: :alien:Auto Buf Generate
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v3
      - name: Buf Build
        uses: bufbuild/buf-setup-action@v1.5.0
      - name: Action Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
  
      - name: Install GRPC Gateway
        run: go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
      - name: Install Protobuf
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Install GRPC Protoc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Install Protoc Open API
        run: go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
        
      - run: echo $GITHUB_ACTOR

      - name: Check Buf Version
        run: buf --version
      - name: Set Path
        run: export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Run Buf Generate
        run: buf generate
      - name: Commit and push changes
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "${{ env.EMAIL_ACTOR }}"
          git pull

          git commit --allow-empty -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
