name: Protobuf

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: bufbuild/buf-setup-action@v1.5.0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: eWaterCycle/setup-grpc@v5
        with:
           grpc-version: 1.30.2
      
      - run: buf --version
      
      - run: export PATH="$PATH:$(go env GOPATH)/bin"

      - run: buf generate
