name: Protobuf

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: asd
        uses: actions/checkout@v3 
      - uses: bufbuild/buf-setup-action@v1.5.0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: protoc-gen-grpc-gateway@latest
        with:
           go-version: 1.18

      - uses: protoc-gen-go@latest
        with:
           go-version: 1.18

      - uses: protoc-gen-go-grpc@latest
        with:
           go-version: 1.18

      - uses: protoc-gen-openapiv2@latest
        with:
           go-version: 1.18
      
      - run: buf --version
      
      - run: export PATH="$PATH:$(go env GOPATH)/bin"

      - run: buf generate
