name: Protobuf

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up grpc
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - uses: bufbuild/buf-setup-action@v1.5.0
      
      - name: Set up buf
         run: buf --version
     
      - run: export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Set up grpc
         run: buf generate
